server:
  port: 7070
eureka:
  client:
    service-url:
      #用来指定注册服务中心地址
      defaultZone: http://localhost:1111/eureka/
  instance:
    instance-id: orderService
    #设置访问路径可以显示ip地址
    prefer-ip-address: true

spring:
  #配置数据库连接信息
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  application:
      name: order-service
#mybatis配置信息
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.neu.order_service.domain
