server:
  port: 9090

eureka:
  client:
    service-url:
      #用来指定注册服务中心地址
      defaultZone: http://localhost:1111/eureka/
  #instance:
    #instance-id: productService
    #设置访问路径可以显示ip地址
    prefer-ip-address: true

    lease-expiration-duration-in-seconds: 5  #服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 30  #服务续约(renew)的间隔，默认为30秒


spring:
  application:
      name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.neu.product_service.domain
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
  mapper-locations: classpath:/mapper/*Mapper.xml #指定映射文件所在路径